# set language of ci
language: c
# set compiler of ci
compiler: gcc
# set os of ci
os: 
  - osx

# run the script
script:
  # go to repo source directory
  - cd ${TRAVIS_BUILD_DIR} 
  # call makefile that 
  - make -f Makefile compile_all