language: c
compiler: gcc

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - cd wp1
  - gcc exerc_1_1.c -o exerc_1_1